baseURL = "https://evemu.dev/"
languageCode = "en-us"
title = "EVEmu"
description = "EVEmu is a server emulator for EVE Online"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "EVEmu Project"

[[menu.main]]
    name = "About"
    weight = -100
    url = "/about/"
[[menu.main]]
    name = "Wiki"
    weight = -100
    url = "https://wiki.evemu.dev"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Project Status"
    weight = -100
    url = "https://wiki.evemu.dev/wiki/Crucible_Project_Status"
[[menu.main]]
    name = "Forums"
    weight = -100
    url = "https://forums.evemu.dev"